### ISSUE TITLE
How to inference on single image and draw the bbox on the image?

### ISSUE THREAD

**Issue by aixiaodewugege** [fredzzhang/pvic#30]
Thank you for your kind words!
I'd like to evaluate the model on my dataset and visualize the outcomes. How can I proceed with this?

**Comment by fredzzhang** [comment]
Hi @aixiaodewugege,

The inference code is in the `inference.py` script, but it hasn't been cleaned up yet. I'm currently occupied by a few other things and will clean up the repo in September.

Fred.

**Comment by fredzzhang** [comment]
Hi @aixiaodewugege,

The codebase for inference and visualisation has now been updated.

Cheers,
Fred.
