### ISSUE TITLE
The problem in your code???

### ISSUE THREAD

**Issue by ZhouGuangP** [fredzzhang/pvic#31]
I noticed in your paper published at ICCV2023, it is mentioned that Layer normalization is used before concatenating spatial and content features to avoid numerical overflow and ensure stable training. However, I couldn't find this part in the code. So, I always get the wrong with 'Hoi loss is nan'?
![image](https://github.com/fredzzhang/pvic/assets/108053656/95d4c2be-c46c-416a-abf4-aad131a3997c)

**Comment by fredzzhang** [comment]
Hi @ZhouGuangP,

The layer normalisation is included in the `MultiModalFusion` module. A similar issue with `nan` loss was reported in #29 and was resolved by using multiple GPUs. Were you using a single GPU?

Fred.
