### ISSUE TITLE
What's the module "upt" in inference.py?

### ISSUE THREAD

**Issue by musicBoxes** [fredzzhang/pvic#32]
I try to run the inference.py to to test the model and get error `ModuleNotFoundError: No module named 'upt'`. After running `pip install upt` and executing the inference.py again, the program prints error: `ImportError: cannot import name 'build_detector' from 'upt' (/opt/conda/envs/pvic/lib/python3.8/site-packages/upt/__init__.py)`. 

I think I misunderstand the source of upt. And I find a UPT model from [UPT: Unary–Pairwise Transformers](https://github.com/fredzzhang/upt). Is this source right? If so, how to combine it with your project?

**Comment by yaoyaosanqi** [comment]
Your guess is correct. You need to read the readme in the UPT carefully.

**Comment by fredzzhang** [comment]
Hi @musicBoxes,

I have been a bit busy lately, and have not cleaned up the code for this work. I will most likely wrap it up by the end of the month. In the meantime, I think you could just change the name of the module to `pvic` and it should work.

Fred.

**Comment by fredzzhang** [comment]
Hi @musicBoxes,

The codebase for inference and visualisation has now been updated.

Cheers,
Fred.
