### ISSUE TITLE
About pre-trained weight of object detector

### ISSUE THREAD

**Issue by xz-123-new** [fredzzhang/pvic#33]
Thanks for your great work! I have one question for your pretrained weight of object detector when training ViC-H-Defm-DETR-SwinL on HICO-DET, the weight of h-detr: h-defm-detr-swinL-dp0-mqs-lft-iter-2stg-hicodet.pth, how should i choose it from the model zoo in https://github.com/HDETR/H-Deformable-DETR, because there are many models satisfies backbone swin-large, or can i just randomly pick one of them? Thanks !

**Comment by xz-123-new** [comment]
Empirically i find the shape mismatch because of the object class number differs from COCO and HICO-DET, and i wonder where could i load the pretrained weight for HICO-DET, thanks!

**Comment by fredzzhang** [comment]
Hi @xz-123-new,

The weights are slightly different because we fine-tuned H-DETR on HICO-DET, and it only has 80 object classes as opposed to 91 in COCO.

The weights will be release once I'm back from ICCV.

Fred.

**Comment by KPeng9510** [comment]
Hi,

I am also interested in your pretrained weights  on HICO--DET for H-DETR. May I ask when you are planning to upload them :)?

**Comment by fredzzhang** [comment]
Hi @KPeng9510 and @xz-123-new,

I just realised I already uploaded the weights [here](https://github.com/fredzzhang/hicodet/tree/main/detections#train-and-test-advanced-variants-of-detr-on-hico-det) a few months ago. Apologies for the wait.

Fred.

**Comment by fredzzhang** [comment]
Detailed documentation has now been added [here](https://github.com/fredzzhang/pvic/blob/main/docs.md).

Fred.
