### ISSUE TITLE
Timeline for upadating Readme.md

### ISSUE THREAD

**Issue by ZhouGuangP** [fredzzhang/pvic#34]
I am puzzled by the difference between my reproduced results on v-coco and the results reported in the article. I use 2 4090 GPU with batchsize=32 for  reproducing.
![image](https://github.com/fredzzhang/pvic/assets/108053656/59a1ae7c-eb8c-45ff-bfd5-290194d7deb9)

**Comment by fredzzhang** [comment]
Hi @ZhouGuangP,

The V-COCO code went through some major restructuring after the submission. I might have broken something in that process. I'm still trying fix it.

In the meantime, were you able to reproduce the performance on HICO-DET?

Fred.

**Comment by ZhouGuangP** [comment]
> Hi @ZhouGuangP,
> 
> The V-COCO code went through some major restructuring after the submission. I might have broken something in that process. I'm still trying fix it.
> 
> In the meantime, were you able to reproduce the performance on HICO-DET?
> 
> Fred.

Yes. I reproduced the performance on HICO-DET, it is next to the results reported in your paper. The performance is 35.44map on full,31.06map on rare 35.44 on none-rare. Thanks for your nice work.

**Comment by winnerwu6** [comment]
Hello, when will your training and evaluation code on the V-COCO data set be updated? My recent work requires your code very much. I will be very grateful if you can update it! !

**Comment by fredzzhang** [comment]
The documentation has now been updated.

Fred.
