### ISSUE TITLE
Mistake when skipping images.

### ISSUE THREAD

**Issue by yaoyaosanqi** [fredzzhang/pvic#39]
Hi @fredzzhang,

We have a tricky problem.
```Skip image when there are no valid human-object pairs
            if len(x_keep) == 0:
                ho_queries.append(torch.zeros(0, self.repr_size, device=device))
                paired_indices.append(torch.zeros(0, 2, device=device, dtype=torch.int64))
                prior_scores.append(torch.zeros(0, 2, self.num_verbs, device=device))
                object_types.append(torch.zeros(0, device=device, dtype=torch.int64))
                positional_embeds.append({})
                continue
```
The absence of human is dealt with here. （x_keep==0）

https://github.com/fredzzhang/pvic/blob/b02d77ee08dd24a875ba1db2e9ca7eb8b15a6252/transformers.py#L179

```   q_p = self.q_attn_qpos_proj(q_pos["box"])
        k_p = self.q_attn_kpos_proj(q_pos["box"])
```

When x_keep==0 is an empty dictionary, it results in:
```  File "/root/autodl-tmp/pvicx/pvic.py", line 628, in forward
    cc = self.clipdecoder(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/autodl-tmp/pvicx/transformers.py", line 905, in forward
    pair = q_pos["pair_spatial"]
KeyError: 'pair_spatial'
```
Here "pair_spatial" denotes the features formed by the concatenation of human and object (from DETR). The feature encounters x_keep==0 and reports an error. We have found that your positional_embeds will also have x_keep==0, but your code works fine.

We try to rewrite ```positional_embeds.append({})``` as a tensor type for ```positional_embeds.append(torch.zeros(0, 1, self.repr_size, device=device))```, but this null tensor causes subsequent code to continue to report errors. How should I modify this part of the code to work correctly?

**Comment by fredzzhang** [comment]
Hi @yaoyaosanqi,

The zero-size queries are handled [here](https://github.com/fredzzhang/pvic/blob/b02d77ee08dd24a875ba1db2e9ca7eb8b15a6252/transformers.py#L241C4-L244) in the `TransformerDecoder` class, and should not proceed into the `TransformerDecoderLayer` class.

Fred.

**Comment by yaoyaosanqi** [comment]
Thanks, our model works fine.
