### ISSUE TITLE
HICO-DET link and download script seems down

### ISSUE THREAD

**Issue by RenatoNogFer** [fredzzhang/pvic#44]
"download.sh" returns 404 error.

**Comment by fredzzhang** [comment]
Hi @RenatoNogFer,

The link was probably updated. You can go to the official [website](https://websites.umich.edu/~ywchao/hico/), find the file in google drive. Then copy the file ID and replace the old file ID in the `download.sh` script.

Fred.

**Comment by YangJae96** [comment]
@fredzzhang HI.

Same here. The download link is down.  "download.sh" returns 404 error.

The official website request an account but I dont have it, so I cant download the dataset on my own.

Could you provided extra link or google drive?!

Thanks in advance.
