### ISSUE TITLE
some question about hyperparameters of PViC with resnet50

### ISSUE THREAD

**Issue by jasminethurder** [fredzzhang/pvic#45]
Thank you for your excellent work!!
When using your code on hico-det, the mAP with the swin-large backbone is normal, but with the resnet50 backbone, the mAP is only 33.6. I'm wondering if this could be due to the hyperparameters? I cloned your repository quite early; have you made any updates since then? Thank you again for your great work.

**Comment by fredzzhang** [comment]
Hi @jasminethurder,

Thanks for taking an interest in our work. I don't think I changed anything, but it's probably worth it to just do a `git pull` anyways. If you still don't get the reported performance, maybe try some different seeds.

Fred.

**Comment by jasminethurder** [comment]
I will try this way, thank you very much!
