### ISSUE TITLE
NaN when I use a DETR that I fine tuned

### ISSUE THREAD

**Issue by JonasFerreiraSilva** [fredzzhang/pvic#48]
Hello, I have a problem when trying to use pvic with a “modified” DETR, I performed a fine tune on the DETR which is found within its repository, when running with the base DETR it works, but with the DETR weights modified by running as follows:

![unnamed](https://github.com/fredzzhang/pvic/assets/36899346/745dc6e9-13cf-4087-9e9a-a0e35f2c944f)

It ends up failing and giving this error:

![Capturar2](https://github.com/fredzzhang/pvic/assets/36899346/9ba7b56b-6b7e-464f-bd6c-e4730bffde9a)

I found my problem similar to the last two comments on this problem [here](https://github.com/fredzzhang/upt/issues/35)

Do you have any suggestions on how I can solve this issue?

**Comment by fredzzhang** [comment]
Hi @JonasFerreiraSilva,

I think the NaN loss only happens occasionally during training. Perhaps you could skip those bad batches by zeroing out the gradient when the loss is NaN. You could do something like this
```python
loss_dict['cls_loss'] = torch.nan_to_num(loss_dict['cls_loss'])
```

Cheers,
Fred.

**Comment by hellog2n** [comment]
@JonasFerreiraSilva 

Did you solve this problem? I faced the same error and I modified my code in the 191 line `utils.py` according to @fredzzhang [comments ](https://github.com/fredzzhang/pvic/issues/48#issuecomment-2073870598) but the loss is 0.0000. 

```def _on_each_iteration(self):
        loss_dict = self._state.net(
            *self._state.inputs, targets=self._state.targets)
        if loss_dict['cls_loss'].isnan():
            loss_dict['cls_loss'] = torch.nan_to_num(loss_dict['cls_loss'])
            print(f"The HOI loss is NaN for rank {self._rank}")```

**Comment by fredzzhang** [comment]
Hi @hellog2n,

If that doesn't solve the issue, I think you need to add that function somewhere earlier in the network. See [this post] for reference.

Since it's normally the spatial features that cause the issue, you can add it [here](https://github.com/fredzzhang/pvic/blob/main/pvic.py#L138).
```python
# Compute spatial features
pairwise_spatial = compute_spatial_encodings(
    [boxes[x],], [boxes[y],], [image_sizes[i],]
)
pairwise_spatial = torch.nan_to_num(pairwise_spatial)
```

**Comment by hellog2n** [comment]
@fredzzhang Thank you for your responding! I solved. :)

**Comment by morrisalp** [comment]
@hellog2n Can you share what exactly you did that solved this? Was it what @fredzzhang suggested?

**Comment by YangJae96** [comment]
@morrisalp  Hi, did you solve the problem??
