### ISSUE TITLE
How to obtain the metrics of Default (DT) mode and Known-Object (KO) mode on the hico-det dataset?

### ISSUE THREAD

**Issue by AngleBeats147753** [fredzzhang/pvic#54]
Hello! I'm very grateful for your work achievements. I encountered a problem when conducting the test. I sincerely hope to get your help.

How to obtain the metrics of Default (DT) mode and Known-Object (KO) mode on the hico-det dataset?
The current eval will only output the map of full, rare, and none-rare for one mode.

**Comment by fredzzhang** [comment]
Hi @AngleBeats147753,

The mAP returned from the Python evaluation script is the default mode. To get results for the know-object mode, you need to cache the detections in Matlab format and evaluate it using the code provided by the original HO-RCNN repo. The command to cache detection in Matlab format is included in the [docs](https://github.com/fredzzhang/pvic/blob/main/docs.md).

Fred.
