### ISSUE TITLE
video data

### ISSUE THREAD

**Issue by LHYUNMIN** [fredzzhang/pvic#58]
Certainly, performing inference on video data is possible??

The UPT README mentions that inference has been conducted on video data or similar content.

**Comment by fredzzhang** [comment]
Hi @LHYUNMIN,

The model can only process an image at a time. However, you can still run the model on the frames of a video individually and aggregate the results in the end. The demo video on the UPT homepage was produced exactly that way.

Hope that answers your question.

Fred.
