### ISSUE TITLE
training error for hicodet

### ISSUE THREAD

**Issue by hurrrrrrtui** [fredzzhang/pvic#59]
Dear sir,
    I am a newcomer to this field. I want to train the HICO dataset on a 4070ti GPU, where the batch size is set to 16 and detector='base'. But the result is an error from Nan. The same code did not report any errors when training the VCOCO dataset. How should I make changes?

**Comment by hurrrrrrtui** [comment]
@fredzzhang

**Comment by fredzzhang** [comment]
Hi @hurrrrrrtui,

Please refer to [this post](https://github.com/fredzzhang/pvic/issues/48#issuecomment-2119547746) for details.

Fred.
