### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by YangJae96** [fredzzhang/pvic#60]
Hi. 

I'm trying to train SWIN-L backbone based model on hico-det.

```
# Training
DETR=advanced python main.py --backbone swin_large --use-checkpoint \
                             --drop-path-rate 0.5 \
                             --num-queries-one2one 900 \
                             --num-queries-one2many 1500 \
                             --pretrained checkpoints/h-defm-detr-swinL-dp0-mqs-lft-iter-2stg-hicodet.pth \
                             --output-dir outputs/pvic-h-defm-detr-swinL-hicodet
```
I've successfully loaded the pretrained weights and the model seems to train well until epoch1.

![image](https://github.com/user-attachments/assets/42e9fe06-cdef-40fa-b424-ddb45a0126b1)

However, after epoch 2, the performance drops weirdly and loss goes to Nan..

![image](https://github.com/user-attachments/assets/fd3be0e6-93e1-446f-be61-79cdb38b3967)

I've used only 1 GPU with a batch-size of 16, and used A100 GPU with CUDA 11.8 and torch verson 2.3.1.

Could I get some help?

**Comment by fredzzhang** [comment]
Hi @YangJae96,

Please refer to this [post](https://github.com/fredzzhang/pvic/issues/48#issuecomment-2119547746). Let mw know if it still doesn't solve your problem.

Fred.

**Comment by YangJae96** [comment]
@fredzzhang  Hi,

I've tried all commens in the post you gave, such as 
```
  loss_dict = self._state.net(
      *self._state.inputs, targets=self._state.targets)
  if loss_dict['cls_loss'].isnan():
      loss_dict['cls_loss'] = torch.nan_to_num(loss_dict['cls_loss'])
      print(f"The HOI loss is NaN for rank {self._rank}")
```

```
# Compute spatial features
pairwise_spatial = compute_spatial_encodings(
    [boxes[x],], [boxes[y],], [image_sizes[i],]
)
pairwise_spatial = torch.nan_to_num(pairwise_spatial)
```

but still get loss Nan in every iteration during training.

I used batch size of 16 with 1 GPU.

``
DETR=advanced python3 main.py --backbone swin_large --use-checkpoint \
                             --drop-path-rate 0.5 \
                             --num-queries-one2one 900 \
                             --num-queries-one2many 1500 \
                             --pretrained checkpoints/h-defm-detr-swinL-dp0-mqs-lft-iter-2stg-hicodet.pth \
                             --output-dir outputs/pvic-h-defm-detr-swinL-hicodet-b16 --batch-size 16``

**Comment by fredzzhang** [comment]
Hi @YangJae96,

What `torch.nan_to_num` does is to zero out `nan` values. So if the loss is still `nan`, the source needs to be pinpointed. Could you isolate the batch of data when `nan` was first observed and try to step through the code in debug mode? In this way, you will be able to find where the `nan` values first appear. Then you can just call `torch.nan_to_num` there and zero it out.

Hope this helps.

Cheers,
Fred.

**Comment by YangJae96** [comment]
@fredzzhang  Hi,

I think training is working fine now. 
But when I tried to use the swin backbone trained weight on single image inference,  some weird error comes.

**RuntimeError: Not implemented on the CPU**

``
File "/home/work/workplace/pvic/inference.py", line 117, in main
    output = model([image_tensor])
    return self._call_impl(*args, **kwargs)
  File "/home/work/anaconda3/envs/vos_hoi/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/work/anaconda3/envs/vos_hoi/lib/python3.10/site-packages/torch/cuda/amp/autocast_mode.py", line 123, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/work/workplace/pvic/h_detr/models/ops/modules/ms_deform_attn.py", line 157, in forward
    output = MSDeformAttnFunction.apply(
  File "/home/work/anaconda3/envs/vos_hoi/lib/python3.10/site-packages/torch/autograd/function.py", line 598, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/work/anaconda3/envs/vos_hoi/lib/python3.10/site-packages/torch/cuda/amp/autocast_mode.py", line 123, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/work/workplace/pvic/h_detr/models/ops/functions/ms_deform_attn_func.py", line 38, in forward
    output = MSDA.ms_deform_attn_forward(
RuntimeError: Not implemented on the CPU
``

Its working fine for ResNet50 model inference. 
I used the below command.
```
DETR=advanced python3 inference.py --backbone swin_large --drop-path-rate 0.5 --num-queries-one2one 900 --num-queries-one2many 1500 --resume outputs/pvic-h-defm-detr-swinL-hicodet-b16-seed10/best.pth --action 36
```

I actually used **--use-checkpoint** option to train the model.

Is there a way to load the SWIN backbone trained weights and use it for inference?

**Comment by fredzzhang** [comment]
Hi @YangJae96,

The `swin_large` backbone uses deformable DETR instead of the vanilla DETR, which is only implemented with CUDA support. That's why you can run ResNet with CPU but it doesn't work with Swin transformer. You just need to run inference on GPU.

Fred.
