### ISSUE TITLE
data set

### ISSUE THREAD

**Issue by LUYUuuum** [fredzzhang/pvic#61]
Hi, when I want to use my own data instead of vcoco for training, where should I change in the code first, I can't find all the changes by myself, looking forward to your reply!

**Comment by LUYUuuum** [comment]
![Screenshot 2024-11-21 145446](https://github.com/user-attachments/assets/3b9c4e2a-f6a0-4af7-8326-b02bb76feaf3)

**Comment by fredzzhang** [comment]
Hi @LUYUuuum,

You need to implement your own dataset class, similar to [this one](https://github.com/fredzzhang/hicodet/blob/main/hicodet.py#L52). The `__getitem__` method is probably the most important one there. You need to make sure your dataset returns the data in the same format. In addition to this, you need to add a correspondence table between object classes and the target HOI classes, similar to [this](https://github.com/fredzzhang/pvic/blob/main/main.py#L72).

I think that should be it. You should be able to other details in the codebase as well.

Cheers,
Fred.

**Comment by LUYUuuum** [comment]
Hi, I'm glad to receive your reply, but I still can't read the annotations after the modification, I would like to know if the model has a minimum requirement for the resolution and number of datasets?
WARNING: Collected results are empty. Return zero AP for class 0.
WARNING: Collected results are empty. Return zero AP for class 1.
WARNING: Collected results are empty. Return zero AP for class 2.
Epoch 2 =>      mAP: 0.0000.
Looking forward to your answer.

**Comment by fredzzhang** [comment]
The resolutions of the images vary a lot in the original dataset, so I don't think that's an issue. Many rare classes in the HICO-DET dataset have few than 10 training examples, some of them with only 1 training image.
