### ISSUE TITLE
weights

### ISSUE THREAD

**Issue by LUYUuuum** [fredzzhang/pvic#64]
Hi, I would like to know how the weights of the dataset are obtained and how I should get the initial weights for the custom dataset
![权重](https://github.com/user-attachments/assets/f8e9575e-5585-4114-8cd3-a4d96bbc8e4f)

**Comment by fredzzhang** [comment]
Hi @LUYUuuum,

I assume you are referring to the fine-tuned detector weights. You can refer to the instructions [here](https://github.com/fredzzhang/hicodet/tree/main/detections#train-and-test-advanced-variants-of-detr-on-hico-det) to fine-tune the detector yourself.

Fred.

**Comment by LUYUuuum** [comment]
Okay, but do I need to rebuild the environment when I fine-tune the model?

**Comment by fredzzhang** [comment]
The same environment should work.
